# space for new cloud specific settings?

# all settings below are present in service's local configuration file (values might differ)
server:
  port: 0

app:
  kafka:
    topics:
      my-topic: emailNotifications

spring:
  datasource:
    password: 12345
    url: jdbc:postgresql://localhost:5432/MyDB
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE