server.port=8080
spring.application.name=user-service

# url address to register microservices
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.datasource.url=jdbc:postgresql://localhost:5432/MyDB
spring.datasource.username=postgres
spring.datasource.password=12345

app.kafka.topics.my-topic=emailNotifications
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.jpa.hibernate.ddl-auto=update
# Format the SQL for readability
spring.jpa.properties.hibernate.format_sql=true
# Log the SQL statements
logging.level.org.hibernate.SQL=DEBUG
# Log the binding parameters (for modern Spring Boot 3+ / Hibernate 6+)
logging.level.org.hibernate.orm.jdbc.bind=TRACE
